FROM node:alpine

WORKDIR /app

COPY ./package.json .
RUN npm install

# actually we don't need it in dev mode
# but we leave it as a remonder to have smth like this in prod mode
COPY . .

CMD ["npm", "run", "start"]
