### 48af332a1d310cb62c80ab2443ccfea91e20002a0b8288f22379e4071ef18c86@group.calendar.google.com

### first req
GET https://cloudresourcemanager.googleapis.com/v3/projects/cal-ex-434916
Authorization: Bearer ya29...


###
GET https://www.googleapis.com/calendar/v3/calendars/48af332a1d310cb62c80ab2443ccfea91e20002a0b8288f22379e4071ef18c86@group.calendar.google.com
Authorization: Bearer ya29...

###
GET https://www.googleapis.com/calendar/v3/users/me/calendarList
Authorization: Bearer ya29...


###
POST /token HTTP/1.1
Host: oauth2.googleapis.com
Content-Type: application/x-www-form-urlencoded

code=4/P7q7W91a-oMsCeLvIaQm6bTrgtp7&
client_id=your_client_id&
client_secret=your_client_secret&
redirect_uri=https%3A//oauth2.example.com/code&
grant_type=authorization_code
